# -*- coding: utf-8 -*-
# Part of AIC HRM Pro. See LICENSE file for full copyright and licensing details.
"""Build the Odoo Apps Store upload for the suite.

One zip per module, because that is what the store takes. Working files
never ship: translation drafts, byte-code caches, the local documentation
folder with real customer data in it.

Two priced listings, not one. An HR director buys the performance suite; a
delivery or PM director buys staffing. Merging them into a single 155 USD
product means neither buyer recognises it as theirs, so each app carries its
own price and its own landing page.

aic_hrm_brand is deliberately NOT built. It exists to remove the
platform vendor's own branding, which is fine for a direct on-premise
delivery under LGPL but is not something to submit to that vendor's
store. It ships with the customer hand-off instead.

Usage:
    python tools/build_store_package.py [--series 19.0] [--dest dist]
    python tools/build_store_package.py --series 18.0     # source defaults to build/18.0
"""
import argparse
import ast
import os
import pathlib
import shutil
import zipfile

STORE_MODULES = [
    # Performance suite: one paid listing plus the modules it installs.
    'aic_hrm_base',
    'aic_okr_kpi',
    'aic_hrm_library',
    'aic_hrm_review',
    'aic_hrm_project',
    'aic_hrm_sale',
    'aic_hrm_pro',
    # Staffing: a second paid listing that shares no dependency with the suite,
    # plus two free connectors. The connectors are published separately because
    # auto_install only fires once the code is on disk - buying the app does not
    # fetch a module the app does not depend on.
    'aic_hrm_match',
    'aic_hrm_match_okr',
    'aic_hrm_match_timesheet',
]
# Listings a customer actually buys. Everything else in STORE_MODULES is
# installed BY a listing and must never carry a price of its own, or the store
# shows one product at two prices.
PRICED_APPS = {'aic_hrm_pro', 'aic_hrm_match'}

# The staffing app is sold to a different buyer and must stay installable on
# its own. Nothing here may appear in its dependency tree.
PERFORMANCE_SUITE = {'aic_hrm_base', 'aic_okr_kpi', 'aic_hrm_review',
                     'aic_hrm_library', 'aic_hrm_pro'}
STANDALONE_APPS = {
    'aic_hrm_match': {'hr', 'hr_skills', 'project', 'mail', 'web'},
}
WITHHELD = {'aic_hrm_brand': 'debrands the platform vendor - direct delivery only'}

# Odoo Apps vendor guidelines: "the name of the app must be explicit and should
# contain no more than 25 characters."
MAX_LISTING_NAME = 25

# Where each series' source tree lives. The 18.0 tree is generated by
# tools/backport_18.py and is not the same directory as the 19.0 sources -
# packaging 18.0 from addons_hrm would ship untransformed Odoo-19 API.
DEFAULT_SOURCES = {
    '19.0': 'addons_hrm',
    '18.0': 'build/18.0',
}

EXCLUDE_DIRS = {'__pycache__', '.pytest_cache', '.ruff_cache'}
EXCLUDE_SUFFIX = ('.pyc', '.pyo', '.draft', '.orig', '.rej')


def read_manifest(module_dir):
    text = (module_dir / '__manifest__.py').read_text(encoding='utf-8')
    return ast.literal_eval(text)


def check(module_dir, manifest, is_app, series):
    """Refuse to ship a module the store would bounce."""
    problems = []
    if manifest.get('license') != 'OPL-1':
        problems.append('license is %r, expected OPL-1'
                        % manifest.get('license'))
    version = str(manifest.get('version', ''))
    if not version.startswith('%s.' % series):
        problems.append('version %r is not %s.x' % (version, series))
    name = str(manifest.get('name', ''))
    if len(name) > MAX_LISTING_NAME:
        problems.append('name is %d chars, the store allows %d: %r'
                        % (len(name), MAX_LISTING_NAME, name))
    # The archive is built from the module directory alone, so a LICENSE at the
    # repository root reaches no zip at all. An OPL-1 product handed over
    # without its licence text is a legal defect.
    if not (module_dir / 'LICENSE').exists():
        problems.append('no LICENSE in the module directory')
    if not (module_dir / 'static/description/icon.png').exists():
        problems.append('no static/description/icon.png')
    if is_app:
        for key in ('price', 'currency', 'support', 'images'):
            if not manifest.get(key):
                problems.append('priced listing has no %r' % key)
        if not (module_dir / 'static/description/index.html').exists():
            problems.append('no static/description/index.html')
        for image in manifest.get('images', []):
            if not (module_dir / image).exists():
                problems.append('images entry missing on disk: %s' % image)
    else:
        if manifest.get('price'):
            problems.append('bundled module carries a price')
        if manifest.get('application'):
            problems.append('bundled module is flagged as an application')
    # Translation is owed by whoever defines the screens. A meta module that
    # only bundles others and ships demo data has no UI strings of its own, so
    # demanding a catalogue from it would fail the build over nothing.
    if defines_ui(module_dir) and not (module_dir / 'i18n/vi.po').exists():
        problems.append('module defines UI but ships no i18n/vi.po')
    return problems


def defines_ui(module_dir):
    """True when the module contributes screens or business objects.

    Used to decide whether a missing translation catalogue is a defect: a
    bundle module (demo data plus a store listing, no models and no views)
    genuinely has nothing to translate.
    """
    return any((module_dir / part).is_dir()
               for part in ('models', 'views', 'wizard', 'report'))


def add_module(zip_path, module_dir, module):
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as archive:
        for root, dirs, files in os.walk(module_dir):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for name in sorted(files):
                if name.endswith(EXCLUDE_SUFFIX):
                    continue
                full = pathlib.Path(root) / name
                # The store unpacks into addons/, so the module directory
                # itself has to be the top level inside the archive.
                arc = pathlib.Path(module) / full.relative_to(module_dir)
                archive.write(full, arc.as_posix())
    return zip_path.stat().st_size


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dest', default='dist')
    parser.add_argument('--series', default='19.0', choices=sorted(DEFAULT_SOURCES),
                        help='Odoo series to package')
    parser.add_argument('--source', default=None,
                        help='source tree (defaults to the one for --series)')
    args = parser.parse_args()

    source_arg = args.source or DEFAULT_SOURCES[args.series]
    source = pathlib.Path(source_arg).resolve()
    if not source.is_dir():
        raise SystemExit(
            'source tree %s does not exist.%s' % (
                source,
                '\nRun `python tools/backport_18.py` first.'
                if args.series == '18.0' else ''))

    dest = pathlib.Path(args.dest).resolve() / args.series
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    failures = []
    built = 0
    total = 0
    for module in STORE_MODULES:
        module_dir = source / module
        manifest = read_manifest(module_dir)
        problems = check(module_dir, manifest, module in PRICED_APPS, args.series)
        if problems:
            failures.append((module, problems))
            continue
        size = add_module(dest / ('%s.zip' % module), module_dir, module)
        total += size
        built += 1
        print('%-18s %6.1f KB  v%s  %s' % (module, size / 1024,
                                           manifest['version'],
                                           manifest['name']))

    for module, why in WITHHELD.items():
        print('%-18s WITHHELD  (%s)' % (module, why))

    if failures:
        print('\nNOT PACKAGED:')
        for module, problems in failures:
            for problem in problems:
                print('  %-18s %s' % (module, problem))
        raise SystemExit(1)

    print('\n%d archives, %.1f KB total -> %s' % (built, total / 1024, dest))


if __name__ == '__main__':
    main()
