# -*- coding: utf-8 -*-
# Part of AIC HRM Pro. See LICENSE file for full copyright and licensing details.
{
    'name': 'AIConnect HRM - Sales Bridge',
    'version': '18.0.1.0.0',
    'category': 'Human Resources/Performance',
    'summary': 'Sales KPIs fed by real quotations, orders and invoices - no manual entry',
    'description': """
Connects AIConnect HRM Pro KPI targets to Odoo Sales and Invoicing.

Provides:

- Per-salesperson automatic actuals on KPI targets: quotation count,
  confirmed order count, confirmed order revenue, invoiced revenue
- Monthly draft period results generated by a daily cron; managers keep the
  confirmation step
- sale.order and account.move allowlisted for generic metric sources
""",
    'author': 'AIPOWER CO., LTD',
    'website': 'https://github.com/trungtm78/aic_hrm_pro',
    'license': 'OPL-1',
    'depends': ['aic_okr_kpi', 'sale'],
    'data': [
        'data/aic_hrm_sale_data.xml',
        'views/aic_hrm_sale_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
